### ISSUE TITLE
Redis限制连接数

### ISSUE THREAD

**Issue by HelloWorld1018** [netease-im/camellia#146]
Module: [e.g. camellia-redis-proxy、camellia-delay-queue]
Version: [e.g. v1.1.10]
Content: [e.g. xxxx has a bug]

直连Redis运行一段时间后，客户端能够自动退出，有如下异常堆栈：
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
[ioredis] Unhandled error event: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error: Command queue state error. If you can reproduce this, please report it. Last error: ERR max number of clients reached
    at DataHandler.shiftCommand (F:\CODE\JsStudy\cache\node_modules\ioredis\built\DataHandler.js:164:27)
    at DataHandler.returnError (F:\CODE\JsStudy\cache\node_modules\ioredis\built\DataHandler.js:33:27)
    at JavascriptRedisParser.returnError (F:\CODE\JsStudy\cache\node_modules\ioredis\built\DataHandler.js:15:22)
    at JavascriptRedisParser.execute (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:542:14)
    at Socket.<anonymous> (F:\CODE\JsStudy\cache\node_modules\ioredis\built\DataHandler.js:25:20)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on Redis instance at:
    at DataHandler.shiftCommand (F:\CODE\JsStudy\cache\node_modules\ioredis\built\DataHandler.js:168:24)
    at DataHandler.returnError (F:\CODE\JsStudy\cache\node_modules\ioredis\built\DataHandler.js:33:27)
    [... lines matching original stack trace ...]
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

Process finished with exit code 1

**Comment by HelloWorld1018** [comment]
DataHandler.js
![image](https://github.com/netease-im/camellia/assets/58578720/bfc74255-6cd3-4a4d-8e92-8b623209b720)

**Comment by HelloWorld1018** [comment]
如果是链接Proxy，会一直循环打印如下报错，客户端也不会退出：
[ioredis] Unhandled error event: ReplyError: ERR max number of clients reached
    at parseError (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: ERR max number of clients reached
    at parseError (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: ERR max number of clients reached
    at parseError (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: ERR max number of clients reached
    at parseError (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:302:14)
[ioredis] Unhandled error event: ReplyError: ERR max number of clients reached
    at parseError (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (F:\CODE\JsStudy\cache\node_modules\redis-parser\lib\parser.js:302:14)
