### ISSUE TITLE
dynamic-conf 配置简单地址启动报错

### ISSUE THREAD

**Issue by tms-c** [netease-im/camellia#164]
Module: [camellia-redis-proxy]
Version: [v1.2.19-latest]
Content: [
----------启动方式
quick-start-package

----------application.yml配置文件
application.yml:
camellia-redis-proxy:
  transpond:
    type: local 
    local:
      type: complex
      json-file: resource-table.json
      dynamic: true 

----------resource-table.json
resource-table.json: redis-cluster://@10.0.5.105:6470,10.0.5.136:7470,10.0.5.136:6471,10.0.5.105:7471,10.0.5.105:7472
或者
resource-table.json: redis://@10.0.5.105:7472
都会报相同的错

---------错误日志如下
Caused by: com.netease.nim.camellia.redis.base.exception.CamelliaRedisException: java.lang.NumberFormatException: For input string: "7472
"
	at com.netease.nim.camellia.redis.base.resource.RedisResourceUtil.parseResourceByUrl(RedisResourceUtil.java:416)
	at com.netease.nim.camellia.redis.base.resource.RedisResourceUtil.checkResourceTable(RedisResourceUtil.java:34)
	at com.netease.nim.camellia.redis.proxy.springboot.CamelliaRedisProxyUtil.parse(CamelliaRedisProxyUtil.java:120)

]

**Comment by caojiajun** [comment]
配置文件能不能格式化一下，看不出来，或者直接加微信hdnxttl沟通
