### ISSUE TITLE
CamelliaRedisException: not redis resource是个什么异常？

### ISSUE THREAD

**Issue by 904648702** [netease-im/camellia#8]
通过k8s对服务进行部署，报了一个not redis resource的异常，我自己检查代码文件和本地测试都是对的，有点不懂了

**Comment by 904648702** [comment]
2021-02-03 03:00:54.220 INFO 1 --- [ restartedMain] c.p.redisproxy.RedisProxyApplication : Starting RedisProxyApplication v0.0.1-SNAPSHOT using Java 1.8.0_281 on redis-proxy-0.redis-proxy.camellia-test.svc.cluster.local with PID 1 (/usr/lib/redis-proxy-0.0.1-SNAPSHOT.jar started by root in /)

2021-02-03 03:00:54.224 INFO 1 --- [ restartedMain] c.p.redisproxy.RedisProxyApplication : No active profile set, falling back to default profiles: default

2021-02-03 03:00:54.300 INFO 1 --- [ restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable

2021-02-03 03:00:55.139 WARN 1 --- [ restartedMain] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commandInvoker' defined in class path resource [com/netease/nim/camellia/redis/proxy/springboot/CamelliaRedisProxyConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netease.nim.camellia.redis.proxy.command.CommandInvoker]: Factory method 'commandInvoker' threw exception; nested exception is com.netease.nim.camellia.redis.exception.CamelliaRedisException: not redis resource

2021-02-03 03:00:55.154 INFO 1 --- [ restartedMain] ConditionEvaluationReportLoggingListener :

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2021-02-03 03:00:55.184 ERROR 1 --- [ restartedMain] o.s.boot.SpringApplication : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'commandInvoker' defined in class path resource [com/netease/nim/camellia/redis/proxy/springboot/CamelliaRedisProxyConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netease.nim.camellia.redis.proxy.command.CommandInvoker]: Factory method 'commandInvoker' threw exception; nested exception is com.netease.nim.camellia.redis.exception.CamelliaRedisException: not redis resource

at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658) ~[spring-beans-5.3.3.jar:5.3.3]

at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.3.jar:5.3.3]

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336) ~[spring-beans-5.3.3.jar:5.3.3]

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179) ~[spring-beans-5.3.3.jar:5.3.3]

at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571) ~[spring-beans-5.3.3.jar:5.3.3]

**Comment by 904648702** [comment]
已排查出来，是配置文件写错了...
