### ISSUE TITLE
[Camellia-redis-proxy] Redis cluster: CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by tasszz2k** [netease-im/camellia#80]
### 1. Issue
- I try to use the Redisson to connect to the `camellia redis proxy` and test `LockExamples`, but always get an error:
```log
[main] INFO org.redisson.Version - Redisson 3.10.6
[redisson-netty-1-26] INFO org.redisson.connection.pool.MasterPubSubConnectionPool - 1 connections initialized for 10.50.69.8/10.50.69.8:6381
[redisson-netty-1-3] INFO org.redisson.connection.pool.MasterConnectionPool - 32 connections initialized for 10.50.69.8/10.50.69.8:6381
>>>>>> start thread
Exception in thread "Thread-0" org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot. channel: [id: 0x0559429c, L:/10.79.xx.xx:51149 - R:10.50.xx.xx/10.50.xx.xx:6381] command: (EVAL), params: [if (redis.call('hexists', KEYS[1], ARGV[3]) == 0) then return nil;end; local counter = redis.call('h..., 2, lock, redisson_lock__channel:{lock}, 0, 30000, f46f747b-a31b-4d38-bb7a-9acb9b96a4e4:46]
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:351)
	at org.redisson.client.handler.CommandDecoder.decodeCommand(CommandDecoder.java:199)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:139)
	at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:114)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### 2. Setup/Configurations
- Camellia version 1.1.9
- Redis resource is a cluster redis
- **(*)** Using `converterPlugin` with implementation is `DefaultTenancyNamespaceKeyConverter`
 `converter.key.className=com.netease.nim.camellia.redis.proxy.plugin.converter.DefaultTenancyNamespaceKeyConverter`
- Use this example: [redisson/LockExamples.java
](https://github.com/redisson/redisson-examples/blob/master/locks-synchronizers-examples/src/main/java/org/redisson/example/locks/LockExamples.java)
- My test class:
```java
public class LockExamples {

    public static void main(String[] args) throws InterruptedException {
        Config config = new Config();

        // rediss - defines to use SSL for Redis connection
        config.useSingleServer()
                .setAddress("redis://127.0.0.1:6380") // this is camellia-redis-proxy
                .setClientName("camellia_13_tass") // tenant to a cluster redis
                .setTimeout(100000);
        RedissonClient redisson = Redisson.create(config);

        RLock lock = redisson.getLock("lock");
        lock.lock(2, TimeUnit.SECONDS);

        Thread t = new Thread(() -> {
            System.out.println(">>>>>> start thread");
            RLock lock1 = redisson.getLock("lock");
            lock1.lock();
            lock1.unlock();
            System.out.println(">>>>>> done");
        });

        t.start();
        t.join();

        redisson.shutdown();
    }

}
```

### 3. Trace/Debug
- The `redisson` will put 2 keys into redis: `lock` and `redisson_lock__channel:{lock}`
- If correct, both of those keys should be in the same slot, but in reality, they are not. Leads to exception: `org.redisson.client.RedisException: CROSSSLOT Keys in request don't hash to the same slot.`
- I debug the `camellia-redis-proxy` and discover that:
  + after the convert key plugin: 2 keys above will be: 
    * `lock` -> `13|tass|lock`  
    * and `redisson_lock__channel:{lock}` -> `13|tass|redisson_lock__channel:{lock}`
  + this leads to the above 2 keys no longer are the same slot 
- At this line, after converting key, 2 keys are not the same slot 
 -> the result of `int slot = RedisClusterCRC16Utils.checkSlot(keys); ` is `-1` -> throw exception here:
https://github.com/netease-im/camellia/blob/814316b0ca1c7f34d240e258e8f0ae2d92f4b46a/camellia-redis-proxy/src/main/java/com/netease/nim/camellia/redis/proxy/upstream/cluster/AsyncCamelliaRedisClusterClient.java#L212-L218

### 4. Solutions
- I'm not sure, but maybe the order of plugins is the problem
 pls help me check this issue, @caojiajun  
 
 thank you.

**Comment by tasszz2k** [comment]
pls help me check this issue, @caojiajun thank you.

**Comment by caojiajun** [comment]
redission, rename `lock` to `{lock}`

**Comment by caojiajun** [comment]
I have no good way to solve this problem

**Comment by tasszz2k** [comment]
> redission, rename `lock` to `{lock}`

`lock` and `redisson_lock__channel:{lock}` are 2 keys generated by the `redission`, also we cannot modify that

**Comment by caojiajun** [comment]
try a simple lock implements?

https://github.com/netease-im/camellia/blob/master/docs/redis-template/toolkit.md

**Comment by tasszz2k** [comment]
> try a simple lock implements?
> 
> https://github.com/netease-im/camellia/blob/master/docs/redis-template/toolkit.md

my existing applications use the `redission` to connect to redis and many other people too, so we can't force them to do so

this is exactly a bug, so I think we need the plan to fix that

**Comment by tasszz2k** [comment]
root cause: The handle converter plugin and the sharding function in the core module of the camellia-redis-proxy are to blame for this problem, which does not just occur with Redisson. That might cause further potential bugs.

**Comment by tasszz2k** [comment]
**Update:**  I have an idea:

- In this case, ex: 
  + `lock` -> `13|tass|lock`  
  + `redisson_lock__channel:{lock}` -> `13|tass|redisson_lock__channel:{lock}`
- we will pre-handle before pushing into the redis cluster:
  + if a key has any hashtag -  curly braces (`{`, `}`) ==> keep original:  `13|tass|redisson_lock__channel:{lock}`
  + otherwise, we put curly braces (`{`, `}`) into the key following by rule of the `ConverterPlugin`: `13|tass|lock`  --> `13|tass|{lock}`
  
_Let me know what you think of this._

**Comment by tasszz2k** [comment]
hmm, whenever we get keys we have to put them into curly braces if it is not present?
```
10.50.69.105:6380> mget {lock}  redisson_lock__channel:{lock}
10.50.69.105:6380>  ... ...
```
 it doesn't seem very good.

**Comment by tasszz2k** [comment]
ah, can we handle it from `Converter Plugin` - `DefaultTenancyNamespaceKeyConverter`?

**Comment by caojiajun** [comment]
it seems not very good.

**Comment by tasszz2k** [comment]
**just draft**
`DefaultTenancyNamespaceKeyConverter` could be like this:

```java
public class DefaultTenancyNamespaceKeyConverter implements KeyConverter {

    private static final String SEPARATOR_STRING = "|";
    private static final byte[] OPEN_CURLY_BRACE = Utils.stringToBytes("{");
    private static final byte[] CLOSE_CURLY_BRACE = Utils.stringToBytes("}");

    @Override
    public byte[] convert(CommandContext commandContext, RedisCommand redisCommand, byte[] originalKey) {
        if (commandContext.getBid() == null || commandContext.getBgroup() == null || commandContext.getBid() <= 0) {
            return originalKey;
        }
        byte[] prefix = Utils.stringToBytes(commandContext.getBid() + SEPARATOR_STRING + commandContext.getBgroup() + SEPARATOR_STRING);
        byte[] keyAfterAppendHashTag;
        if (!isOriginalKeyContainHashTag(originalKey)) {
            keyAfterAppendHashTag = new byte[originalKey.length + OPEN_CURLY_BRACE.length + CLOSE_CURLY_BRACE.length];
            System.arraycopy(OPEN_CURLY_BRACE, 0, keyAfterAppendHashTag, 0, OPEN_CURLY_BRACE.length);
            System.arraycopy(originalKey, 0, keyAfterAppendHashTag, OPEN_CURLY_BRACE.length, originalKey.length);
            System.arraycopy(CLOSE_CURLY_BRACE, 0, keyAfterAppendHashTag, OPEN_CURLY_BRACE.length + originalKey.length, CLOSE_CURLY_BRACE.length);
        } else {
            keyAfterAppendHashTag = originalKey;
        }

        byte[] convertedKey = new byte[keyAfterAppendHashTag.length + prefix.length];
        System.arraycopy(prefix, 0, convertedKey, 0, prefix.length);
        System.arraycopy(keyAfterAppendHashTag, 0, convertedKey, prefix.length, keyAfterAppendHashTag.length);
        return convertedKey;
    }


    @Override
    public byte[] reverseConvert(CommandContext commandContext, RedisCommand redisCommand, byte[] convertedKey) {
        if (commandContext.getBid() == null || commandContext.getBgroup() == null || commandContext.getBid() <= 0) {
            return convertedKey;
        }
        byte[] prefix = Utils.stringToBytes(commandContext.getBid() + SEPARATOR_STRING + commandContext.getBgroup() + SEPARATOR_STRING);
        if (convertedKey.length < prefix.length) {
            return convertedKey;
        }
        boolean prefixMatch = true;
        for (int i = 0; i < prefix.length; i++) {
            if (prefix[i] != convertedKey[i]) {
                prefixMatch = false;
                break;
            }
        }
        if (!prefixMatch) {
            return convertedKey;
        }
        byte[] originalKey = new byte[convertedKey.length - prefix.length];
        System.arraycopy(convertedKey, prefix.length, originalKey, 0, originalKey.length);

        if (isOriginalKeyAsHashTag(originalKey)) {
            // remove hash tag
            byte[] keyHasBeenRemoveCurlyBraces = new byte[originalKey.length - OPEN_CURLY_BRACE.length - CLOSE_CURLY_BRACE.length];
            System.arraycopy(originalKey, OPEN_CURLY_BRACE.length, keyHasBeenRemoveCurlyBraces, 0, keyHasBeenRemoveCurlyBraces.length);
            return keyHasBeenRemoveCurlyBraces;
        }
        return originalKey;

    }

    /**
     * @param key key
     * @return true if original key is a hashtag
     */
    private boolean isOriginalKeyAsHashTag(byte[] key) {
        return return key.length >= 2 && key[0] == '{' && key[key.length - 1] == '}';
    }


    /**
     * Check if original key contains curly braces
     *
     * @param key key
     * @return true if original key contains curly braces
     */
    private boolean isOriginalKeyContainHashTag(byte[] key) {
        for (byte b : key) {
            if (b == '{') {
                return true;
            }
        }
        return false;
    }
}
```

**Comment by tasszz2k** [comment]
> **just draft** `DefaultTenancyNamespaceKeyConverter` could be like this:

This solution has only one issue: the key `lock` and the `{lock}` will be the same key = `13|tass|{lock}`.

**Comment by caojiajun** [comment]
maybe we should use different cluster rather than one cluster with different key-prefix

**Comment by tasszz2k** [comment]
> maybe we should use different cluster rather than one cluster with different key-prefix

The main reason we want to use `camellia-redis-proxy` as redis-proxy is the sharing of a redis resource/ multi-tenancy feature

without it, -50% of feature points 
:"((

**Comment by caojiajun** [comment]
> > **just draft** `DefaultTenancyNamespaceKeyConverter` could be like this:
> 
> This solution has only one issue: the key `lock` and the `{lock}` will be the same key = `13|tass|{lock}`.
> 
> Of course, the `lock` and the `redisson_lock__channel:{lock}` will be hashed to the same slot.

if acceptable, you can try it.

**Comment by tasszz2k** [comment]
You appear to see some issues with this.
let's talk to me, bro

**Comment by caojiajun** [comment]
I means, the CustomKeyConverter like that is suitable for your case, but not others, this is reasonable.

**Comment by tasszz2k** [comment]
I was able to fix this problem more effectively - a better solution while still handling the converter plugin.
I need to test more test cases then I will create PR tomorrow. 
: D
